spring.application.name=pnc_insurance

spring.datasource.url=jdbc:postgresql://localhost:5432/vm-tsc-slide-deck
spring.datasource.username=postgres
spring.datasource.password=Password@01

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=4567
